insert into autoconnector_config (line_pk, line) values (10, '#productive rules');
insert into autoconnector_config (line_pk, line) values (20, '#################');
insert into autoconnector_config (line_pk, line) values (30, '');
insert into autoconnector_config (line_pk, line) values (40, '#standard pairing');
insert into autoconnector_config (line_pk, line) values (50, '*-VH-CH<''%CH1%''>-H-CH<''%CH2%''>-CH<''%CH3%''>-*,*-VL-CL-*=>3&7<1>');
insert into autoconnector_config (line_pk, line) values (60, '');
insert into autoconnector_config (line_pk, line) values (70, '#scFv');
insert into autoconnector_config (line_pk, line) values (80, 'VH-X<''?G?S''>-VL-*=>1&3<n>');
insert into autoconnector_config (line_pk, line) values (90, '*-VH-X<''?G?S''>-VL=>1&3<n>');
insert into autoconnector_config (line_pk, line) values (100, 'VL-X<''?G?S''>-VH-*=>1&3<n>');
insert into autoconnector_config (line_pk, line) values (110, '*-VL-X<''?G?S''>-VH=>1&3<n>');
insert into autoconnector_config (line_pk, line) values (120, '');
insert into autoconnector_config (line_pk, line) values (130, '#scFAB LC+HC on one chain ');
insert into autoconnector_config (line_pk, line) values (140, '*-VL-CL-X<''?G?S''>-VH-CH<''%CH1%''>-H-CH<''%CH2%''>-CH<''%CH3%''>-*=>1&4<n>');
insert into autoconnector_config (line_pk, line) values (150, '*-VL-CL-X<''?G?S''>-VH-CH<''%CH1%''>-H-CH<''%CH2%''>-CH<''%CH3%''>-*=>2&6<n>');
insert into autoconnector_config (line_pk, line) values (160, '');
insert into autoconnector_config (line_pk, line) values (170, '#scFab connect V');
insert into autoconnector_config (line_pk, line) values (180, 'VH-CH<''%CH1%''>-X-VL-CL-X<''?G?S''>-*=>1&4<n>');
insert into autoconnector_config (line_pk, line) values (190, '*-X<''?G?S''>-VH-CH<''%CH1%''>-X-VL-CL=>2&5<n>');
insert into autoconnector_config (line_pk, line) values (200, 'VL-CL-X<''?G?S''>-VH-CH<''%CH1%''>-X-*=>1&4<n>');
insert into autoconnector_config (line_pk, line) values (210, '*-VL-CL-X<''?G?S''>-VH-CH<''%CH1%''>-X=>1&4<n>');
insert into autoconnector_config (line_pk, line) values (220, '');
insert into autoconnector_config (line_pk, line) values (230, '#scFab connect C');
insert into autoconnector_config (line_pk, line) values (240, 'VH-CH<''%CH1%''>-X-VL-CL-X<''?G?S''>-*=>3&5<n>');
insert into autoconnector_config (line_pk, line) values (250, '*-X<''?G?S''>-VH-CH<''%CH1%''>-X-VL-CL=>4&6<n>');
insert into autoconnector_config (line_pk, line) values (260, 'VL-CL-X<''?G?S''>-VH-CH<''%CH1%''>-X-*=>2&6<n>');
insert into autoconnector_config (line_pk, line) values (270, '*-VL-CL-X<''?G?S''>-VH-CH<''%CH1%''>-X=>2&6<n>');
